export const ContainerActivType = {
  increase_performance_life: "increase_performance_life",
  increase_performance_strong: "increase_performance_strong",
  increase_performance_armor: "increase_performance_armor",
  persReplay: "persReplay",
  getAvatar: "getAvatar",
  getPersArea: "getPersArea",
  getName: "getName",
  getCounter: "getCounter",
  cheats_life: "1111",
  cheats_strong: "2222",
  cheats_armor: "3333",
  check: "check",
  getCheck: "getCheck",
  create_monstr: "create_monstr",
  life_editing: "life_editing",
};
